default:
  homepage:
    title: Homepage | Test Homepage | Mandragora Thuringia
    navbar:
      termine: Termine
      band: Band
      shop: Shop
      kontakt: Kontakt
    partnerLinks:
      mddRecords: MDD Records
      pyramidStrings: Pyramid Strings
    welcomeContent:
      imageSubtitle:  Album Release – 04. November 2022
   
