default:
  homepage:
    title: Homepage | Test Homepage | Mandragora Thuringia
    partnerLinks:
      mddRecords: MDD Records
      pyramidStrings: Pyramid Strings
    welcomeContent:
      imageSubtitle:  Album Release – 04. November 2022
   
